# Generated by Django 5.0.1 on 2026-02-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0026_company_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency_symbol',
        ),
    ]
