# Generated by Django 5.0.1 on 2026-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0028_update_user_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone Number', max_length=20),
        ),
    ]
