# Generated by Django 5.0.1 on 2026-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0029_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='openrouter_model_2',
            field=models.CharField(blank=True, help_text='OpenRouter Model:2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='openrouter_model_3',
            field=models.CharField(blank=True, help_text='OpenRouter Model:3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='openrouter_model',
            field=models.CharField(blank=True, default='google/gemini-flash-1.5:free', help_text='OpenRouter Model:1', max_length=255, null=True),
        ),
    ]
