# Generated by Django 5.0.1 on 2026-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0030_company_openrouter_model_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand Name', max_length=255, null=True),
        ),
    ]
