# Generated by Django 5.0.1 on 2026-02-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0031_company_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Public quotation number (auto-generated, non-sequential)', max_length=50, null=True, unique=True),
        ),
    ]
