# Generated by Django 5.0.1 on 2026-02-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0032_quotation_quotation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="Prefix for quotation numbers (e.g. 'synq')", max_length=50)),
                ('numberfield', models.PositiveIntegerField(default=0, help_text='Current/last used number')),
            ],
            options={
                'verbose_name': 'Quotation Number Generator',
                'verbose_name_plural': 'Quotation Number Generators',
            },
        ),
    ]
