# Generated by Django 5.0.1 on 2026-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0033_quotgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quotation_numberfield',
            field=models.PositiveIntegerField(default=0, help_text='Last used quotation running number (for reference).'),
        ),
        migrations.AddField(
            model_name='company',
            name='quotation_prefix',
            field=models.CharField(blank=True, help_text="Custom quotation prefix (e.g. 'synq'). If empty, first 3 letters of company name are used.", max_length=50, null=True),
        ),
    ]
