# Generated by Django 5.0.1 on 2026-02-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0035_make_quotation_number_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.client'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Is this quotation a draft?'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this quotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_quotations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of quotations created by this user'),
        ),
    ]
