# Generated by Django 5.2.11 on 2026-02-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0036_quotation_customer_quotation_is_draft_quotation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_quotations',
        ),
    ]
