# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0038_user_created_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by_type',
            field=models.CharField(blank=True, help_text="Type of creator: 'company' or 'user'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='ID of user who created this customer (if created by user)', null=True),
        ),
    ]

