# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0040_user_updated_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username (optional, for login)', max_length=255, null=True, unique=True),
        ),
    ]

