# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0041_user_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_by_type',
            field=models.CharField(blank=True, help_text="Type of updater: 'company' or 'user'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, help_text='ID of user who last updated this customer (if updated by user)', null=True),
        ),
    ]

