# Generated by Django 5.0.1 on 2026-02-16 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0042_client_updated_by_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, help_text="Normalized service name (e.g., 'cleaning service', 'madurai to chennai')", max_length=255)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Minimum price seen for this service', max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, help_text='Maximum price seen for this service', max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, help_text='Average price calculated from all occurrences', max_digits=12)),
                ('unit_type', models.CharField(blank=True, help_text="Unit type: 'per day', 'per hour', 'fixed', 'per km', etc.", max_length=50, null=True)),
                ('usage_count', models.PositiveIntegerField(default=1, help_text='Number of times this service has been used in quotations')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this service was used in a quotation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Price Memory',
                'verbose_name_plural': 'Service Price Memories',
                'ordering': ['-usage_count', '-last_used'],
                'indexes': [models.Index(fields=['service_name'], name='service_name_idx'), models.Index(fields=['-usage_count'], name='usage_count_idx'), models.Index(fields=['-last_used'], name='last_used_idx')],
                'unique_together': {('service_name',)},
            },
        ),
    ]
