# Generated by Django 5.0.1 on 2026-02-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0043_servicepricememory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePriceMemory',
        ),
    ]
